"""Locate the wrapping band in the approved frame strip without including free tails.

Run with Pillow: --input public/assets/design/ribbon-sequence --out
src/intro/ribbon-band-regions.mjs. This measures regions, never crops or rewrites
the source frames. The first connected component crossing the physical fold
and inner slice boundary is the wrapping band. All registration stays fixed.
"""
import argparse
from collections import deque
import json
from pathlib import Path
from PIL import Image

p = argparse.ArgumentParser(description=__doc__)
p.add_argument('--input', type=Path, required=True)
p.add_argument('--out', type=Path, required=True)
args = p.parse_args()
manifest = json.loads((args.input / 'manifest.json').read_text())
assert (manifest['width'], manifest['height']) == (480, 1920)
bottoms = []
for index, name in enumerate(manifest['frames']):
    if index >= manifest['releaseCompleteFrame']:
        bottoms.append([0, 0])
        continue
    with Image.open(args.input / name) as image:
        alpha = image.getchannel('A')
    pair = []
    for left, inner, fold in [(0, 71, 36), (408, 0, 35)]:
        pixels = list(alpha.crop((left, 0, left + 72, 1920)).getdata())
        seen = bytearray(len(pixels))
        candidates = []
        for i, value in enumerate(pixels):
            if value < 8 or seen[i]:
                continue
            queue = deque([i]); seen[i] = 1
            top = bottom = i // 72
            touches_inner = touches_fold = False
            while queue:
                offset = queue.popleft(); x, y = offset % 72, offset // 72
                top, bottom = min(top, y), max(bottom, y)
                touches_inner |= x == inner; touches_fold |= x == fold
                neighbors = ([offset-1] if x else []) + ([offset+1] if x < 71 else []) + ([offset-72] if y else []) + ([offset+72] if y < 1919 else [])
                for other in neighbors:
                    if not seen[other] and pixels[other] >= 8:
                        seen[other] = 1; queue.append(other)
            if touches_inner and touches_fold:
                candidates.append((top, bottom))
        # Two transparent padding rows include the antialiased silhouette.
        pair.append(min(1920, min(candidates)[1] + 3) if candidates else 0)
    bottoms.append(pair)
text = '// Generated by scripts/ribbon/measure_band_regions.py. Source frames remain unchanged.\n'
text += 'export const RIBBON_BAND_SOURCE_SHA256 = ' + json.dumps(manifest['framePack']['sha256']) + ';\n'
text += '// Bottom pixel of the wrapping band on each side. Zero after complete paper release.\n'
text += 'export const RIBBON_BAND_BOTTOMS = ' + json.dumps(bottoms, separators=(',', ':')) + ';\n'
args.out.write_text(text, encoding='utf-8')
